coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto 
        flags: 
          - unit
        paths: 
          - "tobac"

# what folders and files to ignore
ignore:
  - */tests/.*
  - setup.py

